Fix forgotten argument in README
This change fixes the following error when trying the example:

```
Traceback (most recent call last):
  File ".../src/app.py", line 5, in <module>
    connexionApp = connexion.App(specification_dir='./swagger/')
TypeError: __init__() missing 1 required positional argument: 'import_name'
```