(v2) Fix build of OpenAPI Console UI URL if servers/url is missing or "/"
Fixes #2093

Changes proposed in this pull request:
- Use "/" if the escaped app base path is the empty string, to adjust for
  new behavior of Flask and/or Werkzeug, which raises this error if the
  swagger.yaml file has no servers/url entry or servers/url with value "/":

  werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '/._openapi_json'.

- Add new test case to check blueprint and url prefix of open API specification
  with servers/url value "/"

- Add new test case to confirm Swagger UI is returned when the specification
  (either OpenAPI or Swagger) has a trivial base path